# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 726d4a2ce1805014e68a2567d65ba73b889155f26b49dd7773d833deeb491bb965de8f6824a10ece446786a3144ea69031cb64efaddee11b4ab2891b8e7b79d2

test:
  secret_key_base: afc73a3e1ab3195c96377a471e3ce7832ef41b72dce34c44645b58adccf9dd2a8e23086a75fd6a5931ddf4da4070504822967f85dcc1ddb57cf05d6ec9688e1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
